version: '3.3'
services:
  assignment1_be:
    container_name: assignment1_be
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - ./data/sessions:/sessions
      - ../:/root/msg_queue_etcd
  nginx_be:
    container_name: nginx_be
    restart: always
    image: "nginx:latest"
    ports:
      - "2379:2379"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - assignment1_be
  # mysql_db:
  #   image: mysql:8.0
  #   restart: always
  #   container_name: assignment1_mysql_db
  #   environment:
  #     MYSQL_ROOT_HOST: '172.17.0.1'
  #     # MYSQL_ROOT_HOST: '127.0.0.1'
  #     MYSQL_DATABASE: 'assignment'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'app_usr'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'pass'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - mysql-db:/var/lib/mysql
  #   networks:
  #     - db_network
# Names our volume
volumes:
  mysql-db:
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge